server:
  port: 8765
spring:
  application:
    name: mycloud
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    #registerWithEureka: false
    #fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8764/eureka/